### ISSUE TITLE
Issue running install

### ISSUE THREAD

**Issue by mhernandorena** [schnoog/klippered#1]
i tried using the github link you provided and it's giving me this error:

wget "https://raw.githubusercontent.com/schnoog/klippered/main/install/Install\_Ender3V3SE\_Klipper.sh" && chmod +x Install\_Ender3V3SE\_Klipper.sh && ./Install\_Ender3V3SE\_Klipper.sh

Connecting to raw.githubusercontent.com (185.199.109.133:443)

wget: note: TLS certificate validation not implemented

wget: can't open 'Install\_Ender3V3SE\_Klipper.sh': File exists

Noy sure if I'm doing it correctly, I go into putty acces the printer as a root user and run that command, then that's the error o get.

**Comment by schnoog** [comment]
Hi, thanks for the feedback. It seems that there's a problem with the TLS certificate (which is quite strange).

You can open the file in the web-browser and copy it's content to a local file, save it, make it executable 
nano WhatEverFileNameYouChose.sh
<paste content>
CTRL+x   -> enter 
chmod +x WhatEverFileNameYouChose.sh
and execute it
./WhatEverFileNameYouChose.sh
